[build]
  # Comando de build
  command = "npm run build"
  # Diretório onde os arquivos estáticos são gerados
  publish = "dist"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[[redirects]]
  # Redireciona todas as requisições para index.html para suportar SPA
  from = "/*"
  to = "/index.html"
  status = 200